title: IT.BR Australia # your site title
author: IT.BR Australia
email: admin@itbr.com.au # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Site da comunidade de brasileiros que trabalham com IT na Australia
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://itbr.com.au" # the base hostname & protocol for your site, e.g. https://example.com
github_username:  itbraustralia # replace with your_github_username or comment to remove link from footer
social:
  name: IT.BR Australia
  links:
    - https://www.facebook.com/itbraustralia
    - https://github.com/itbraustralia

service_worker: true
google_tag_manager: 'UA-119467002-1'

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
